# Generated by Django 4.1.7 on 2023-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_remove_cart_cart_id_alter_cart_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                blank=True,
                default=models.AutoField(primary_key=True, serialize=False),
                max_length=250,
            ),
        ),
    ]
