# Generated by Django 4.1.7 on 2023-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cart_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
