# Generated by Django 4.1.7 on 2023-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_is_admin_remove_account_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="is_superadmin",
            new_name="admin",
        ),
        migrations.AddField(
            model_name="account",
            name="staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
