# Generated by Django 4.1.7 on 2023-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_is_superadmin_account_admin_account_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="images",
            field=models.ImageField(
                default="default_profile_image.jpg", upload_to="photos/profilepicture"
            ),
        ),
    ]
