# Generated by Django 4.1.7 on 2023-06-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="images",
            new_name="profile_images",
        ),
    ]
