# Generated by Django 4.1.7 on 2023-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_final_prize"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="images",
            field=models.ImageField(
                default="default_payment_image.jpg", upload_to="photos/payments"
            ),
        ),
    ]
