# Generated by Django 4.1.7 on 2023-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("SCB", "SCB"),
                    ("K-BANKS", "K-BANKS"),
                    ("Krungsri", "Krungsri"),
                ],
                default="SCB",
                max_length=100,
            ),
        ),
    ]
