# Generated by Django 4.1.7 on 2023-07-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                    ("Approved", "Approved"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
