# Generated by Django 4.1.7 on 2023-08-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_payment_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="tax",
            new_name="shipping",
        ),
    ]
